In [43]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("festival-sanremo-1951-2023.xlsx")

In [3]:
df

,Anno,Periodo,Sede,Presentatore,Partecipanti,Vincitore,Anno in data
0,1951,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951-01-01
1,1952,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952-01-01
2,1953,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953-01-01
3,1954,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954-01-01
4,1955,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955-01-01
...,...,...,...,...,...,...,...
68,2019,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019-01-01
69,2020,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020-01-01
70,2021,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021-01-01
71,2022,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022-01-01
72,2023,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023-01-01

In [4]:
df.loc[:,"anno1"]= df.loc[:,"Anno in data"].dt.year

In [5]:
df.drop(['Anno', 'Anno in data'], axis=1, inplace=True)

In [6]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955
...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023

In [7]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955
...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023

In [8]:
import pandas as pd
import re

def parse_periodo_semplice(periodo_str):
    """
    Estrae data inizio e fine basandosi su:
    - DATA INIZIO: primo numero + prima parola di sole lettere
    - DATA FINE: secondo numero + prima parola di sole lettere dopo il secondo numero
    """
    if pd.isna(periodo_str) or periodo_str == '':
        return None, None
    
    periodo = str(periodo_str).strip()
    
    # Trova tutti i numeri nella stringa
    numeri = re.findall(r'\d+', periodo)
    
    # Trova tutte le parole composte solo da lettere
    parole = re.findall(r'[a-zA-Zàáâäçéèêëíìîïñóòôöúùûüýÿ]+', periodo)
    
    if len(numeri) < 2 or len(parole) < 1:
        return periodo, periodo
    
    # DATA INIZIO: primo numero + prima parola
    data_inizio = f"{numeri[0]} {parole[0]}"
    
    # DATA FINE: secondo numero + prima parola 
    data_fine = f"{numeri[1]} {parole[0]}"
    
    # Se ci sono più parole, la seconda potrebbe essere per la data fine
    if len(parole) > 1:
        data_fine = f"{numeri[1]} {parole[1]}"
    
    return data_inizio, data_fine

In [16]:
import pandas as pd
import re

def parse_periodo_semplice(Periodo_str):
    if pd.isna(Periodo_str) or Periodo_str == '':
        return None, None
    
    Periodo = str(Periodo_str).strip()
    
    # Trova tutti i numeri nella stringa
    numeri = re.findall(r'\d+', Periodo)
    
    # Trova tutte le parole composte solo da lettere
    parole = re.findall(r'[a-zA-Zàáâäçéèêëíìîïñóòôöúùûüýÿ]+', Periodo)
    
    if len(numeri) < 2 or len(parole) < 1:
        return Periodo, Periodo
    
    # DATA INIZIO: primo numero + prima parola
    data_inizio = f"{numeri[0]} {parole[0]}"
    
    # DATA FINE: secondo numero + prima parola 
    data_fine = f"{numeri[1]} {parole[0]}"
    
    # Se ci sono più parole, la seconda potrebbe essere per la data fine
    if len(parole) > 1:
        data_fine = f"{numeri[1]} {parole[1]}"
    
    return data_inizio, data_fine

# Applicazione sul DataFrame df

date_parsed = df['Periodo'].apply(parse_periodo_semplice)
df['data_inizio'] = date_parsed.apply(lambda x: x[0])
df['data_fine'] = date_parsed.apply(lambda x: x[1])

In [17]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1,data_inizio,data_fine
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951,29 gennaio,31 gennaio
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952,28 gennaio,30 gennaio
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953,29 gennaio,31 gennaio
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954,28 gennaio,30 gennaio
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955,27 gennaio,29 gennaio
...,...,...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019,5 febbraio,9 febbraio
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020,4 febbraio,8 febbraio
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021,2 marzo,6 marzo
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022,1 febbraio,5 febbraio
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023,7 febbraio,11 febbraio

In [18]:
df['data_inizio'] = df['data_inizio'].astype(str) + ' ' + df['anno1'].astype(str)
df['data_fine'] = df['data_fine'].astype(str) + ' ' + df['anno1'].astype(str)

In [19]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1,data_inizio,data_fine
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951,29 gennaio 1951,31 gennaio 1951
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952,28 gennaio 1952,30 gennaio 1952
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953,29 gennaio 1953,31 gennaio 1953
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954,28 gennaio 1954,30 gennaio 1954
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955,27 gennaio 1955,29 gennaio 1955
...,...,...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019,5 febbraio 2019,9 febbraio 2019
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020,4 febbraio 2020,8 febbraio 2020
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021,2 marzo 2021,6 marzo 2021
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022,1 febbraio 2022,5 febbraio 2022
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023,7 febbraio 2023,11 febbraio 2023

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Periodo       73 non-null     object
 1   Sede          73 non-null     object
 2   Presentatore  73 non-null     object
 3   Partecipanti  73 non-null     int64
 4   Vincitore     73 non-null     object
 5   anno1         73 non-null     int32
 6   data_inizio   73 non-null     object
 7   data_fine     73 non-null     object
dtypes: int32(1), int64(1), object(6)
memory usage: 4.4+ KB

In [ ]:
def sostituisci_multiplo(mese, numeri):
    """
    Sostituisce più stringhe in un testo utilizzando un dizionario.

    Args:
        testo: La stringa in cui effettuare le sostituzioni.
        sostituzioni: Un dizionario dove le chiavi sono le stringhe da sostituire
                      e i valori sono le stringhe con cui sostituirle.

    Returns:
        La stringa risultante con tutte le sostituzioni applicate.
    """
    for vecchia_stringa, nuova_stringa in sostituzioni.items():
        mese = mese.replace(mese, numero)
    return testo

In [29]:
def sostituisci_multiplo(df, sostituzioni):
    
    for vecchia_stringa, nuova_stringa in sostituzioni.items():
        df['data_inizio'] = df['data_inizio'].replace(vecchia_stringa, nuova_stringa)
    return df['data_inizio']

sostituzioni = {
    " gennaio ": "-01-",
    " febbraio ": "-02-",
    " marzo ": "-03-"
}
df_mod = sostituisci_multiplo(df, sostituzioni)
df_mod

0     29 gennaio 1951
1     28 gennaio 1952
2     29 gennaio 1953
3     28 gennaio 1954
4     27 gennaio 1955
           ...
68    5 febbraio 2019
69    4 febbraio 2020
70       2 marzo 2021
71    1 febbraio 2022
72    7 febbraio 2023
Name: data_inizio, Length: 73, dtype: object

In [30]:
sostituzioni = {
    " gennaio ": "-01-",
    " febbraio ": "-02-",
    " marzo ": "-03-"
}
def sostituisci_multiplo(df, sostituzioni):
    for vecchia_stringa, nuova_stringa in sostituzioni.items():
        df['data_inizio'] = df['data_inizio'].str.replace(vecchia_stringa, nuova_stringa, regex=False)
    return df  # Restituisce il DataFrame, non solo la colonna


df = sostituisci_multiplo(df, sostituzioni)
print(df['data_inizio'].head())

0    29-01-1951
1    28-01-1952
2    29-01-1953
3    28-01-1954
4    27-01-1955
Name: data_inizio, dtype: object

In [32]:
sostituzioni = {
    " gennaio ": "-01-",
    " febbraio ": "-02-",
    " marzo ": "-03-"
}
def sostituisci_multiplo(df, sostituzioni):
    for vecchia_stringa, nuova_stringa in sostituzioni.items():
        df['data_fine'] = df['data_fine'].str.replace(vecchia_stringa, nuova_stringa, regex=False)
    return df  # Restituisce il DataFrame, non solo la colonna


df = sostituisci_multiplo(df, sostituzioni)
print(df['data_fine'].head())

0    31-01-1951
1    30-01-1952
2    31-01-1953
3    30-01-1954
4    29-01-1955
Name: data_fine, dtype: object

In [33]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1,data_inizio,data_fine
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951,29-01-1951,31-01-1951
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952,28-01-1952,30-01-1952
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953,29-01-1953,31-01-1953
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954,28-01-1954,30-01-1954
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955,27-01-1955,29-01-1955
...,...,...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019,5-02-2019,9-02-2019
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020,4-02-2020,8-02-2020
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021,2-03-2021,6-03-2021
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022,1-02-2022,5-02-2022
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023,7-02-2023,11-02-2023

In [44]:
df.loc[:,'data_inizio']= pd.to_datetime(df.loc[:,"data_inizio"],dayfirst = True)

In [45]:
df.loc[:,'data_fine']= pd.to_datetime(df.loc[:,"data_fine"],dayfirst = True)

In [50]:
df

,Periodo,Sede,Presentatore,Partecipanti,Vincitore,anno1,data_inizio,data_fine
0,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi,1951,1951-01-29 00:00:00,1951-01-31 00:00:00
1,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi,1952,1952-01-28 00:00:00,1952-01-30 00:00:00
2,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni,1953,1953-01-29 00:00:00,1953-01-31 00:00:00
3,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla,1954,1954-01-28 00:00:00,1954-01-30 00:00:00
4,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa,1955,1955-01-27 00:00:00,1955-01-29 00:00:00
...,...,...,...,...,...,...,...,...
68,5 - 9 febbraio,Teatro Ariston,Claudio Baglioni,24,Mahmood,2019,2019-02-05 00:00:00,2019-02-09 00:00:00
69,4 - 8 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),32,Diodato (cantante),2020,2020-02-04 00:00:00,2020-02-08 00:00:00
70,2 - 6 marzo,Teatro Ariston,Amadeus (conduttore televisivo),34,Måneskin,2021,2021-03-02 00:00:00,2021-03-06 00:00:00
71,1º-5 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),25,Mahmood,2022,2022-02-01 00:00:00,2022-02-05 00:00:00
72,7-11 febbraio,Teatro Ariston,Amadeus (conduttore televisivo),28,Marco Mengoni,2023,2023-02-07 00:00:00,2023-02-11 00:00:00

In [54]:
df['data_inizio'] = pd.to_datetime(df['data_inizio'])
df['data_fine'] = pd.to_datetime(df['data_fine'])
df['durata_festival'] = (df['data_fine'] - df['data_inizio']).dt.days + 1

In [59]:
df.to_excel("festival_sanremo.xlsx", index=False)